const palette = require('./theme/palette.json');

module.exports = {
  content: ['./App.tsx', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        bg: palette.bg,
        surface: palette.surface,
        surface2: palette.surface2,
        border: palette.border,
        divider: palette.divider,
        ink: palette.ink,
        ink2: palette.ink2,
        ink3: palette.ink3,
        inverse: palette.inverse,
        primary: palette.primary,
        primaryDark: palette.primaryDark,
        primarySoft: palette.primarySoft,
        primarySofter: palette.primarySofter,
        accent: palette.accent,
        accentSoft: palette.accentSoft,
        accentInk: palette.accentInk,
        syncOk: palette.syncOk,
        syncBg: palette.syncBg,
        syncInk: palette.syncInk,
        pending: palette.pending,
        pendingBg: palette.pendingBg,
        pendingInk: palette.pendingInk,
        danger: palette.danger,
        dangerBg: palette.dangerBg,
      },
      fontSize: {
        '2xs': '9px',
        xs: '11px',
        sm: '12px',
        base: '13px',
        md: '14px',
        lg: '15px',
        xl: '18px',
        '2xl': '20px',
        '3xl': '22px',
        '4xl': '28px',
        '5xl': '32px',
        '7xl': '64px',
      },
      letterSpacing: {
        tightest: '-2px',
        tighter: '-1.5px',
        tight: '-0.8px',
        snug: '-0.4px',
        normal: '0px',
        wide: '0.5px',
      },
      borderRadius: {
        xs: `${palette.radii.xs}px`,
        sm: `${palette.radii.sm}px`,
        md: `${palette.radii.md}px`,
        lg: `${palette.radii.lg}px`,
        xl: `${palette.radii.xl}px`,
      },
      fontFamily: {
        ui: ['Manrope_500Medium'],
        'ui-semibold': ['Manrope_600SemiBold'],
        'ui-bold': ['Manrope_700Bold'],
        'ui-extrabold': ['Manrope_800ExtraBold'],
        mono: ['JetBrainsMono_500Medium'],
        'mono-bold': ['JetBrainsMono_700Bold'],
        'mono-extrabold': ['JetBrainsMono_800ExtraBold'],
      },
    },
  },
  plugins: [],
};
