import { StyleSheet } from 'react-native';
import { colors, FONT } from '../../global/themes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 12,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  backBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -8,
  },
  backBtnText: {
    fontFamily: FONT.uiExtra,
    fontSize: 28,
    color: colors.ink,
    lineHeight: 28,
  },
  headerTitleWrap: {
    flex: 1,
  },
  headerTitle: {
    fontFamily: FONT.uiExtra,
    fontSize: 24,
    color: colors.ink,
    letterSpacing: -0.6,
  },
  headerSubtitle: {
    fontFamily: FONT.ui,
    fontSize: 14,
    color: colors.ink2,
    marginTop: 2,
  },
  headerBadge: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 8,
  },
  headerBadgeText: {
    fontFamily: FONT.monoBold,
    fontSize: 12,
    color: colors.ink2,
  },
  body: {
    padding: 20,
    paddingBottom: 100,
    gap: 16,
  },
  producerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: colors.radii.lg,
    padding: 14,
  },
  producerInfo: {
    flex: 1,
    minWidth: 0,
  },
  producerLabel: {
    fontFamily: FONT.uiExtra,
    fontSize: 11,
    color: colors.ink3,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  producerName: {
    fontFamily: FONT.uiBold,
    fontSize: 17,
    color: colors.ink,
    letterSpacing: -0.3,
    marginTop: 2,
  },
  producerFarm: {
    fontFamily: FONT.uiSemi,
    fontSize: 13,
    color: colors.ink2,
  },
  trocarText: {
    fontFamily: FONT.uiBold,
    fontSize: 13.5,
    color: colors.primary,
  },
  volumeSection: {
    gap: 6,
  },
  fieldLabel: {
    fontFamily: FONT.uiBold,
    fontSize: 14,
    color: colors.ink2,
    letterSpacing: -0.1,
  },
  volumeInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: colors.radii.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    paddingHorizontal: 18,
    height: 72,
  },
  volumeInputFocused: {
    borderColor: colors.primary,
  },
  volumeInputField: {
    flex: 1,
    fontFamily: FONT.monoBold,
    fontSize: 28,
    color: colors.ink,
    letterSpacing: -0.6,
    height: '100%',
    padding: 0,
  },
  volumeSuffix: {
    fontFamily: FONT.uiBold,
    fontSize: 22,
    color: colors.ink2,
  },
  photoSection: {
    gap: 6,
  },
  photoLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  photoRequired: {
    fontFamily: FONT.uiBold,
    fontSize: 13,
    color: colors.danger,
  },
  photoPlaceholder: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.surface,
    borderRadius: colors.radii.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: 'dashed',
    padding: 14,
  },
  cameraIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  cameraTextWrap: {
    flex: 1,
  },
  cameraTitle: {
    fontFamily: FONT.uiBold,
    fontSize: 15.5,
    color: colors.ink,
    letterSpacing: -0.2,
  },
  cameraHint: {
    fontFamily: FONT.uiSemi,
    fontSize: 13,
    color: colors.ink2,
    marginTop: 2,
  },
  photoPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.surface,
    borderRadius: colors.radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
  },
  photoPreviewThumb: {
    width: 64,
    height: 64,
    borderRadius: 14,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.border,
    flexShrink: 0,
  },
  photoPreviewInfo: {
    flex: 1,
    gap: 4,
  },
  photoPreviewLabel: {
    fontFamily: FONT.uiBold,
    fontSize: 15,
    color: colors.syncOk,
  },
  offlineWarning: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: colors.pendingBg,
    borderRadius: colors.radii.md,
    padding: 12,
  },
  offlineIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.8,
    borderColor: colors.pendingInk,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  offlineIconText: {
    fontFamily: FONT.monoBold,
    fontSize: 11,
    color: colors.pendingInk,
  },
  offlineText: {
    flex: 1,
    fontFamily: FONT.uiSemi,
    fontSize: 13,
    color: colors.pendingInk,
    lineHeight: 18,
  },
  offlineTextBold: {
    fontFamily: FONT.uiBold,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  confirmBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: colors.radii.md,
    paddingVertical: 16,
  },
  confirmBtnDisabled: {
    backgroundColor: colors.surface2,
  },
  confirmBtnText: {
    fontFamily: FONT.uiExtra,
    fontSize: 15,
    color: colors.contrast,
    letterSpacing: -0.2,
  },
  confirmBtnTextDisabled: {
    color: colors.ink3,
  },
});
